// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitySearchUserController from "./activity_search_user_controller"
application.register("activity-search-user", ActivitySearchUserController)

import AgecheckController from "./agecheck_controller"
application.register("agecheck", AgecheckController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import LegalguardianController from "./legalguardian_controller"
application.register("legalguardian", LegalguardianController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import RangeController from "./range_controller"
application.register("range", RangeController)

import ToggleOpenController from "./toggle_open_controller"
application.register("toggle-open", ToggleOpenController)
