// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivitySearchUserController from "./activity_search_user_controller"
application.register("activity-search-user", ActivitySearchUserController)

import AgecheckController from "./agecheck_controller"
application.register("agecheck", AgecheckController)

import LegalguardianController from "./legalguardian_controller"
application.register("legalguardian", LegalguardianController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import UsearchController from "./usearch_controller"
application.register("usearch", UsearchController)
