+// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgecheckController from "./agecheck_controller"
application.register("agecheck", AgecheckController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import UsearchController from "./usearch_controller"
application.register("usearch", UsearchController)
