require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/membership_histories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MembershipHistory. As you add validations to MembershipHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MembershipHistory.create! valid_attributes
      get membership_histories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      membership_history = MembershipHistory.create! valid_attributes
      get membership_history_url(membership_history)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_membership_history_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      membership_history = MembershipHistory.create! valid_attributes
      get edit_membership_history_url(membership_history)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MembershipHistory" do
        expect {
          post membership_histories_url, params: { membership_history: valid_attributes }
        }.to change(MembershipHistory, :count).by(1)
      end

      it "redirects to the created membership_history" do
        post membership_histories_url, params: { membership_history: valid_attributes }
        expect(response).to redirect_to(membership_history_url(MembershipHistory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MembershipHistory" do
        expect {
          post membership_histories_url, params: { membership_history: invalid_attributes }
        }.to change(MembershipHistory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post membership_histories_url, params: { membership_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested membership_history" do
        membership_history = MembershipHistory.create! valid_attributes
        patch membership_history_url(membership_history), params: { membership_history: new_attributes }
        membership_history.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the membership_history" do
        membership_history = MembershipHistory.create! valid_attributes
        patch membership_history_url(membership_history), params: { membership_history: new_attributes }
        membership_history.reload
        expect(response).to redirect_to(membership_history_url(membership_history))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        membership_history = MembershipHistory.create! valid_attributes
        patch membership_history_url(membership_history), params: { membership_history: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested membership_history" do
      membership_history = MembershipHistory.create! valid_attributes
      expect {
        delete membership_history_url(membership_history)
      }.to change(MembershipHistory, :count).by(-1)
    end

    it "redirects to the membership_histories list" do
      membership_history = MembershipHistory.create! valid_attributes
      delete membership_history_url(membership_history)
      expect(response).to redirect_to(membership_histories_url)
    end
  end
end
