# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/waitlists', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Waitlist. As you add validations to Waitlist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Waitlist.create! valid_attributes
      get waitlists_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      waitlist = Waitlist.create! valid_attributes
      get waitlist_url(waitlist)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_waitlist_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      waitlist = Waitlist.create! valid_attributes
      get edit_waitlist_url(waitlist)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Waitlist' do
        expect do
          post waitlists_url, params: { waitlist: valid_attributes }
        end.to change(Waitlist, :count).by(1)
      end

      it 'redirects to the created waitlist' do
        post waitlists_url, params: { waitlist: valid_attributes }
        expect(response).to redirect_to(waitlist_url(Waitlist.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Waitlist' do
        expect do
          post waitlists_url, params: { waitlist: invalid_attributes }
        end.to change(Waitlist, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post waitlists_url, params: { waitlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested waitlist' do
        waitlist = Waitlist.create! valid_attributes
        patch waitlist_url(waitlist), params: { waitlist: new_attributes }
        waitlist.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the waitlist' do
        waitlist = Waitlist.create! valid_attributes
        patch waitlist_url(waitlist), params: { waitlist: new_attributes }
        waitlist.reload
        expect(response).to redirect_to(waitlist_url(waitlist))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        waitlist = Waitlist.create! valid_attributes
        patch waitlist_url(waitlist), params: { waitlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested waitlist' do
      waitlist = Waitlist.create! valid_attributes
      expect do
        delete waitlist_url(waitlist)
      end.to change(Waitlist, :count).by(-1)
    end

    it 'redirects to the waitlists list' do
      waitlist = Waitlist.create! valid_attributes
      delete waitlist_url(waitlist)
      expect(response).to redirect_to(waitlists_url)
    end
  end
end
