default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>

    - queues: [ real_time, background ]
      threads: 5
      polling_interval: 1
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
