default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: "*"
      threads: 1
      polling_interval: 2
    - queues: [ real_time, background ]
      threads: 1
      polling_interval: 0.5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
