default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        memberships_validation:
          class: ValidateMembershipStatusJob
          schedule: every day at 17:28 in Europe/Rome
        subscriptions_validation:
          class: ValidateSubscriptionStatusJob
          schedule: every day at 17:28 in Europe/Rome
        legal_guardian_cleanup:
          class: DeleteStaleLegalGuardiansJob
          schedule: every minute
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 2
    - queues: [ real_time, background ]
      threads: 5
      processes: 3
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
